ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
  ITERATOR_OPTIONS:
    SHUFFLE: True
SIMULATOR:
  TURN_ANGLE: 30
  AGENT_0:
    SENSORS: ['DEPTH_SENSOR']
    HEIGHT: 0.88
    RADIUS: 0.18
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False

  DEPTH_SENSOR:
    WIDTH: 640
    HEIGHT: 360
    HFOV: 70
    MIN_DEPTH: 0.1
    MAX_DEPTH: 10.0
    POSITION: [0, 0.88, 0]
    NOISE_MODEL: "RedwoodDepthNoiseModel"

  ACTION_SPACE_CONFIG: 'pyrobotnoisy'
  NOISE_MODEL:
    ROBOT: "LoCoBot"
    CONTROLLER: 'Proportional'
    NOISE_MULTIPLIER: 0.5

TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 0.36 # 2 x Agent Radius
  SENSORS: ['POINTGOAL_SENSOR',
            'GPS_SENSOR', 
            'COMPASS_SENSOR',
            'POINTGOAL_WITH_GPS_SENSOR', 
            'POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  POINTGOAL_WITH_GPS_SENSOR:
    GOAL_FORMAT: CARTESIAN
    DIMENSIONALITY: 2
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: CARTESIAN
    DIMENSIONALITY: 2
  POINTGOAL_SENSOR:
    GOAL_FORMAT: CARTESIAN
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal
  MEASUREMENTS: ['DISTANCE_TO_GOAL', "SUCCESS", 'SPL', 'SOFT_SPL']
  SUCCESS:
    SUCCESS_DISTANCE: 0.36 # 2 x Agent Radius

DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  DATA_PATH: data/datasets/pointnav/gibson/v2/{split}/{split}.json.gz
