BASE_TASK_CONFIG_PATH: "configs/tasks/challenge_pointnav2020.local.rgbd.yaml"
TRAINER_NAME: "ddppo"
ENV_NAME: "NavRLEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
VIDEO_OPTION: []
TENSORBOARD_DIR: "tb/lstm-vib-complete-gps-only-v2-flow-emb-bigger-compress-4x"
VIDEO_DIR: "video_dir"
TEST_EPISODE_COUNT: 994
EVAL_CKPT_PATH_DIR: "data/checkpoints/lstm-vib-complete-gps-only-v2-flow-emb-bigger-compress-4x"
NUM_PROCESSES: 6
SENSORS: ["DEPTH_SENSOR"]
CHECKPOINT_FOLDER: "data/checkpoints/lstm-vib-complete-gps-only-v2-flow-emb-bigger-compress-4x"
NUM_UPDATES: 200000
LOG_INTERVAL: 10
CHECKPOINT_INTERVAL: 250

EVAL:
  USE_CKPT_CONFIG: False

# Force PyTorch to be single threaded as
# this improves performance considerably
FORCE_TORCH_SINGLE_THREADED: True

RL:
  SUCCESS_REWARD: 2.5
  PPO:
    # ppo params
    clip_param: 0.2
    ppo_epoch: 4
    num_mini_batch: 2
    value_loss_coef: 0.5
    entropy_coef: 0.01
    lr: 2.5e-4
    eps: 1e-5
    max_grad_norm: 0.5
    num_steps: 128
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: False
    use_linear_lr_decay: False
    reward_window_size: 50
    final_beta: 1e1
    start_beta: 1e-2
    beta_decay_steps: 2.5e7
    decay_start_step: 2.5e7
    use_aux_losses: True
    use_info_bot: True
    use_odometry: False

    use_normalized_advantage: False

    hidden_size: 512

  DDPPO:
    sync_frac: 0.6
    # The PyTorch distributed backend to use
    distrib_backend: NCCL
    # Visual encoder backbone
    pretrained_weights: data/ddppo-models/rs18-gibson-v2-depth-with-noise-v6.pth
    # Initialize with pretrained weights
    pretrained: False
    # Initialize just the visual encoder backbone with pretrained weights
    pretrained_encoder: True
    # Whether or not the visual encoder backbone will be trained.
    train_encoder: False
    # Whether or not the reset the critic linear layer
    reset_critic: True

    # Model parameters
    backbone: resnet18
    rnn_type: LSTM
    num_recurrent_layers: 2
